### ISSUE TITLE
do not follow mute status

### ISSUE THREAD

**Issue by BlasterOverlord** [rileytestut/Delta#220]
Right now delta does not play audio in games if the iphone is muted. I do not like that and would request at least a toggle of some sort to disable that. I want audio to play even if the iphone is in the muted state, just like it is in other apps.

**Comment by jnubz** [comment]
(I'm not the dev, but figured I'd throw in my 2¢) I'm pretty sure that media is the only thing that can override the mute toggle on iOS. This is preferable since I don't want an app to make noise in a quiet room unexpectedly. This does not keep audio from playing in an app if you have headphones on.

**Comment by BlasterOverlord** [comment]
I don't know if this is bug but even with headphones on, there's no audio playing in Delta when the iphone is muted.

**Comment by jnubz** [comment]
That sounds like a legitimate bug.

**Comment by BlasterOverlord** [comment]
for more info:
iPhone: 6s plus
iOS: 15.7.3
Delta emulator version: 1.3.2

**Comment by Catarax** [comment]
It's on the new beta.

**Comment by shanegillio** [comment]
Make sure to look at the  "Respect Mute Switch" setting. When enabled, Delta audio can be muted using the Mute Switch on your device. As well, Delta auto mutes the game audio if you have another app playing audio already.
