### ISSUE TITLE
Most NES Games Load a Black Screen on Tap

### ISSUE THREAD

**Issue by lonkle** [rileytestut/Delta#52]
This issue exists on the latest Stable and Beta Delta releases. You can workaround the issue by making sure you first load the game using the contextual menu (long press) upon opening Delta. After that, Delta will happily play all NES games no matter how you choose to load them. 

(Explained in detail in the #delta-bugs channel on Discord)

**Comment by JoelStickney** [comment]
Here’s a video of the the bug AND how to work around it. 

https://photos.app.goo.gl/iJEdhsGSkD6vXR3eA

And here’s video of me explaining the issue as I’m testing:

https://photos.app.goo.gl/kmWxKu5RQzWsDWCYA

**Comment by chinarut** [comment]
thanks @JoelStickney for the 2nd video explaining the workaround - it works!  Glad I don’t have to have Delta Lite taking up one of my 3 slots anymore :) I did find it interesting that Delta Lite never hangs.

I just got Delta built in Xcode. Waiting for the iOS14 public release so I can start playing around with real-time debugging this issue and squish this one for good!

**Comment by JoelStickney** [comment]
Oh, if you're a Mac Developer in Xcode, are you on the Discord with us (I'm `Lonk` on there)? 

PS. Hope you meant the second video in the first link, since that shows the only way to reliable play games on the NES in Delta rn (by "long pressing" the game). Oh, and it may no longer be a thing in alpha since Riley recently developed a multiple processes hack that reworked the ways the core's work so he might have *accidentally* fixed that in the Delta Alpha build.

**Comment by lonkle** [comment]
This has been fixed in the latest beta. Closing it out.
