### ISSUE TITLE
Will this application be on android??

### ISSUE THREAD

**Issue by shabbirmahmud** [rileytestut/Delta#92]
I hope the devoloper make this app for android too🥺🙏🥺

**Comment by noah978** [comment]
There are no intentions of ever recreating the app to run on android.

**Comment by shabbirmahmud** [comment]
> There are no intentions of ever recreating the app to run on android.

Why 😭😭??

**Comment by kgsbowtie** [comment]
Most likely because there already exists several emulators for android. This project is born out of the fact that iOS doesn't have any emulators because Apple refuses to host emulators on the App Store. Literally this app only exists because this same developer was also able to create the AltStore—an actually useful way to slideload apps to iOS devices. Without AltStore, this app basically would just be some pet project that barely anyone could actually use.

Compare that to Android: Literally anyone can install an APK, regardless of where you get it from. Google cares not. And emulators also do exist on the Play Store. Just download them and try them to see which ones work for you.

**Comment by shabbirmahmud** [comment]
> Most likely because there already exists several emulators for android. This project is born out of the fact that iOS doesn't have any emulators because Apple refuses to host emulators on the App Store. Literally this app only exists because this same developer was also able to create the AltStore—an actually useful way to slideload apps to iOS devices. Without AltStore, this app basically would just be some pet project that barely anyone could actually use.
> 
> Compare that to Android: Literally anyone can install an APK, regardless of where you get it from. Google cares not. And emulators also do exist on the Play Store. Just download them and try them to see which ones work for you.

Bro i checheked all ds emulator bt no emulator supports multiplayer feature.Bt delta for ios supports it and it has many emulators in a one emulator.

**Comment by ianclawson** [comment]
Recreating an app of this scale and technical complexity on an entirely separate platform is a Herculean effort for even the best developers. And where the primary developer has chosen to focus their efforts on iOS development and knows who-knows-how-much about Android development, asking to have this app ported to Android by the Delta team is a very unrealistic request.

That said, because this app is open source, you (or anyone else) are welcome to see how it works and to create an Android equivalent.
